### ISSUE TITLE
设置mssql出错

### ISSUE THREAD

**Issue by EuropeJing** [ericdum/DataVProxy#11]
在config.js里设置mssql后无法链接数据库，提示

已配置DB:
===== [TypeError: this.storage.test is not a function]
1

**Comment by huangronggod** [comment]
@EuropeJing 请问这个问题解决了吗，如何解决的呢，能解答一下么

**Comment by EuropeJing** [comment]
弄好了，我是直接把他连接后的测试代码给注释了。连接后正常。

**Comment by EuropeJing** [comment]
@huangronggod 文件路径：DataVProxy/core/data_source/storage/index.js
第38行`return yield this.storage.test();`注释掉，加一行（也可以直接把第38行改为）`return true;`
不过这样的话程序就不会验证数据库是不是真的连上了。
